### ISSUE TITLE
Test the container

### ISSUE THREAD

**Issue by jbelmont** [jbelmont/containerized-golang-and-vuejs#1]
@nzmoore Do you want to give this a try now.

You should be able to do:

`npm run build`

`npm run dev` 

if the container runs successfully you should be able to go to:

`localhost:8080`

**Comment by nzmoore** [comment]
Jean-Marcel
The build succeeds and the containers start without error.
I can reach localhost:8080 and the page shows a list of users.
The menu links and remove buttons don’t do anything but I think that is as you expect.

Regards Bill Moore
bill@nzmoore.com

**Comment by jbelmont** [comment]
Awesome thanks Bill. Yeah the button and links aren't hooked up yet
